# Generated by Django 4.2.1 on 2023-05-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Subject',
        ),
    ]
