# Generated by Django 4.2.1 on 2023-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_app', '0006_remove_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Phone', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
